"""Tabular data ML plugin (default).

Generates projects for traditional ML with structured/tabular data using
scikit-learn, pandas, and xgboost.
"""

from typing import Dict, List, Any
from mlcli.plugins.base import PluginBase


class TabularPlugin(PluginBase):
    """Plugin for tabular/structured data ML projects."""
    
    name = "tabular"
    description = "Traditional ML with structured data (pandas, sklearn, xgboost)"
    dependencies = ["pandas", "scikit-learn", "xgboost"]
    
    def get_directory_structure(self) -> List[str]:
        """Return minimal directory structure for tabular ML projects."""
        return [
            "data/raw",
        ]
    
    def get_boilerplate_files(self) -> Dict[str, str]:
        """Return essential boilerplate files for tabular ML."""
        return {
            "README.md": self._get_readme(),
            ".gitignore": self._get_gitignore(),
        }
    
    def get_requirements(self) -> str:
        """Return requirements.txt content."""
        return """# ML Assistant CLI
ml-assistant-cli

# Data processing
pandas>=2.0.0
numpy>=1.24.0
scikit-learn>=1.3.0

# ML libraries
xgboost>=1.7.0

# Visualization (optional)
matplotlib>=3.7.0
seaborn>=0.12.0
"""
    
    def get_config_template(self) -> Dict[str, Any]:
        """Return plugin-specific config."""
        return {
            "plugin": "tabular",
            "data": {
                "test_size": 0.2,
                "random_state": 42,
                "target_column": None,
            },
            "model": {
                "algorithms": ["logistic_regression", "random_forest", "xgboost"],
                "cv_folds": 5,
                "hyperparameter_tuning": True,
            },
            "preprocessing": {
                "missing_value_strategy": "auto",
                "scaling_strategy": "standard",
                "encoding_strategy": "auto",
            }
        }
    
    def _get_readme(self) -> str:
        """Get README template."""
        return """# ML Project (Tabular Data)

This project was initialized with **ML Assistant CLI** using the **tabular** plugin.

## Quick Start

```bash
# 1. Add your dataset
cp /path/to/your/data.csv data/raw/

# 2. Preprocess data
mlcli preprocess --input data/raw/data.csv --target target_column

# 3. Train models
mlcli train

# 4. Evaluate performance
mlcli evaluate

# 5. Get AI suggestions
mlcli suggest

# 6. Make predictions
mlcli predict --input new_data.csv --output predictions.csv
```

## Project Structure

```
├── data/
│   └── raw/           # Your raw datasets
├── mlcli.yaml         # ML pipeline configuration
└── README.md
```

Additional directories are created automatically:
- `data/processed/` - Preprocessed data
- `models/` - Trained models
- `reports/` - Evaluation reports

## Configuration

Edit `mlcli.yaml` to customize:
- Target column name
- Model algorithms to try
- Preprocessing strategies
- Hyperparameter tuning settings

## Supported Algorithms

- Logistic Regression
- Random Forest
- XGBoost
- Gradient Boosting
- Support Vector Machine

## Next Steps

1. Add your dataset to `data/raw/`
2. Edit `mlcli.yaml` to set your target column
3. Run `mlcli preprocess` to prepare your data
"""
    
    def _get_gitignore(self) -> str:
        """Get .gitignore template."""
        return """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.env
.venv
env/
venv/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# ML artifacts (generated by mlcli)
data/processed/
models/
reports/
predictions/

# Model files
*.pkl
*.joblib
*.h5
*.hdf5

# Logs
logs/
*.log

# Jupyter
.ipynb_checkpoints/

# Testing
.pytest_cache/
.coverage
htmlcov/
"""
