"""Pydantic schemas for MLCLI artifacts.

This package provides type-safe validation for all JSON artifacts
generated by MLCLI commands:

- DataProfileSchema: data_profile.json (from preprocess)
- TrainingSummarySchema: training_summary.json (from train)
- EvaluationReportSchema: evaluation_report.json (from evaluate)

Usage:
    from mlcli.core.schemas import DataProfileSchema, load_and_validate
    
    # Load and validate a data profile
    profile = load_and_validate("data/processed/data_profile.json", DataProfileSchema)
    print(f"Samples: {profile.n_samples}, Features: {profile.n_features}")
"""

from pathlib import Path
from typing import Any, Dict, Optional, Type, TypeVar, Union

from pydantic import ValidationError

from .base import VersionedArtifact, ArtifactMetadata
from .data_profile import DataProfileSchema, TargetInfo, QualityIssues
from .training_summary import TrainingSummarySchema, TrainingConfig, ModelResult
from .evaluation_report import EvaluationReportSchema, ClassificationMetrics, RegressionMetrics

__all__ = [
    "VersionedArtifact",
    "ArtifactMetadata",
    "DataProfileSchema",
    "TargetInfo",
    "QualityIssues",
    "TrainingSummarySchema",
    "TrainingConfig",
    "ModelResult",
    "EvaluationReportSchema",
    "ClassificationMetrics",
    "RegressionMetrics",
    "load_and_validate",
    "validate_dict",
    "SchemaValidationError",
]

T = TypeVar("T", bound=VersionedArtifact)


class SchemaValidationError(Exception):
    """Raised when artifact validation fails."""
    
    def __init__(self, message: str, errors: Optional[list] = None):
        super().__init__(message)
        self.errors = errors or []


def load_and_validate(
    file_path: Union[str, Path],
    schema_class: Type[T],
    strict: bool = False
) -> T:
    """Load a JSON file and validate it against a Pydantic schema.
    
    Args:
        file_path: Path to JSON file
        schema_class: Pydantic model class to validate against
        strict: If True, raise on unknown fields
        
    Returns:
        Validated Pydantic model instance
        
    Raises:
        FileNotFoundError: If file doesn't exist
        SchemaValidationError: If validation fails
    """
    import json
    
    file_path = Path(file_path)
    
    if not file_path.exists():
        raise FileNotFoundError(f"Artifact file not found: {file_path}")
    
    try:
        with open(file_path, "r") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise SchemaValidationError(f"Invalid JSON in {file_path}: {e}")
    
    return validate_dict(data, schema_class, strict, str(file_path))


def validate_dict(
    data: Dict[str, Any],
    schema_class: Type[T],
    strict: bool = False,
    source: Optional[str] = None
) -> T:
    """Validate a dictionary against a Pydantic schema.
    
    Args:
        data: Dictionary to validate
        schema_class: Pydantic model class
        strict: If True, raise on unknown fields
        source: Optional source identifier for error messages
        
    Returns:
        Validated Pydantic model instance
        
    Raises:
        SchemaValidationError: If validation fails
    """
    try:
        if strict:
            return schema_class.model_validate(data)
        return schema_class.model_validate(data)
    except ValidationError as e:
        errors = e.errors()
        error_messages = []
        
        for error in errors:
            loc = ".".join(str(x) for x in error["loc"])
            msg = error["msg"]
            error_messages.append(f"  - {loc}: {msg}")
        
        source_info = f" in {source}" if source else ""
        raise SchemaValidationError(
            f"Validation failed{source_info}:\n" + "\n".join(error_messages),
            errors=errors
        )
