"""Schema for data_profile.json artifact."""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from .base import VersionedArtifact


class TargetInfo(BaseModel):
    """Information about the target variable."""
    
    name: str = Field(description="Target column name")
    dtype: str = Field(description="Data type of target")
    unique_values: int = Field(ge=0, description="Number of unique values")
    missing_values: int = Field(ge=0, description="Number of missing values")
    task_type: Optional[str] = Field(default=None, description="classification or regression")
    label_mapping: Optional[Dict[str, int]] = Field(default=None, description="Label to index mapping")
    value_counts: Optional[Dict[str, int]] = Field(default=None, description="Value counts for classification")
    
    model_config = {"extra": "forbid"}


class QualityIssues(BaseModel):
    """Data quality issues detected during preprocessing."""
    
    high_missing_columns: List[str] = Field(default_factory=list, description="Columns with >50% missing")
    high_cardinality_columns: List[str] = Field(default_factory=list, description="Categorical columns with >50% unique values")
    constant_columns: List[str] = Field(default_factory=list, description="Columns with only one value")
    duplicate_columns: List[tuple] = Field(default_factory=list, description="Pairs of duplicate columns")
    outlier_columns: List[str] = Field(default_factory=list, description="Columns with significant outliers")
    
    model_config = {"extra": "forbid"}


class DataProfileSchema(VersionedArtifact):
    """Schema for data_profile.json generated by preprocess command.
    
    Contains comprehensive data analysis and preprocessing metadata.
    """
    
    original_shape: tuple[int, int] = Field(description="Original data dimensions (rows, cols)")
    processed_shape: Optional[tuple[int, int]] = Field(default=None, description="Processed data dimensions")
    
    numeric_columns: List[str] = Field(default_factory=list, description="Numeric feature names")
    categorical_columns: List[str] = Field(default_factory=list, description="Categorical feature names")
    feature_names: List[str] = Field(default_factory=list, description="All feature names after preprocessing")
    
    missing_values: Dict[str, int] = Field(default_factory=dict, description="Missing count per column")
    missing_percentage: Dict[str, float] = Field(default_factory=dict, description="Missing % per column")
    duplicates: int = Field(default=0, ge=0, description="Number of duplicate rows")
    
    memory_usage: int = Field(default=0, ge=0, description="Memory usage in bytes")
    
    target_info: Optional[TargetInfo] = Field(default=None, description="Target variable information")
    quality_issues: Optional[QualityIssues] = Field(default=None, description="Detected quality issues")
    
    preprocessing_steps: List[str] = Field(default_factory=list, description="Applied preprocessing steps")
    
    numeric_stats: Optional[Dict[str, Dict[str, float]]] = Field(default=None, description="Numeric column statistics")
    categorical_stats: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Categorical column statistics")
    
    @field_validator('original_shape', 'processed_shape')
    @classmethod
    def validate_shape(cls, v):
        if v is not None:
            if len(v) != 2:
                raise ValueError('Shape must be a tuple of (rows, columns)')
            if v[0] < 0 or v[1] < 0:
                raise ValueError('Shape values must be non-negative')
        return v
    
    @property
    def n_samples(self) -> int:
        """Number of samples in original data."""
        return self.original_shape[0] if self.original_shape else 0
    
    @property
    def n_features(self) -> int:
        """Number of features in original data."""
        return self.original_shape[1] if self.original_shape else 0
    
    @property
    def missing_ratio(self) -> float:
        """Overall missing value ratio."""
        if not self.missing_percentage:
            return 0.0
        return max(self.missing_percentage.values()) if self.missing_percentage else 0.0
    
    @property
    def has_quality_issues(self) -> bool:
        """Check if any quality issues were detected."""
        if not self.quality_issues:
            return False
        return any([
            self.quality_issues.high_missing_columns,
            self.quality_issues.high_cardinality_columns,
            self.quality_issues.constant_columns,
            self.quality_issues.outlier_columns,
        ])
    
    model_config = {
        "json_schema_extra": {
            "description": "Data profile schema for preprocessing artifacts",
            "examples": [{
                "schema_version": "1.0.0",
                "created_at": "2026-02-22T10:30:00",
                "original_shape": [1000, 10],
                "processed_shape": [1000, 15],
                "numeric_columns": ["age", "income"],
                "categorical_columns": ["gender", "city"],
                "missing_values": {"age": 5, "income": 10},
                "target_info": {
                    "name": "target",
                    "dtype": "int64",
                    "unique_values": 2,
                    "task_type": "classification"
                }
            }]
        },
        "extra": "forbid",
    }
