"""Schema for training_summary.json artifact."""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from .base import VersionedArtifact


class TrainingConfig(BaseModel):
    """Configuration used for training."""
    
    algorithms: List[str] = Field(description="List of algorithms trained")
    cv_folds: int = Field(ge=2, default=5, description="Number of cross-validation folds")
    scoring_metric: str = Field(default="accuracy", description="Scoring metric for optimization")
    hyperparameter_tuning: bool = Field(default=True, description="Whether hyperparameter tuning was performed")
    
    model_config = {"extra": "forbid"}


class ModelResult(BaseModel):
    """Result for a single trained model."""
    
    cv_score: float = Field(ge=0.0, le=1.0, description="Cross-validation score")
    val_score: Optional[float] = Field(default=None, description="Validation score if available")
    best_params: Dict[str, Any] = Field(default_factory=dict, description="Best hyperparameters found")
    error: Optional[str] = Field(default=None, description="Error message if training failed")
    
    model_config = {"extra": "forbid"}


class TrainingSummarySchema(VersionedArtifact):
    """Schema for training_summary.json generated by train command.
    
    Contains model training results and configuration.
    """
    
    task_type: str = Field(description="classification or regression")
    best_model_name: Optional[str] = Field(default=None, description="Name of the best performing model")
    best_score: Optional[float] = Field(default=None, ge=0.0, description="Best cross-validation score")
    
    models_trained: int = Field(default=0, ge=0, description="Number of models successfully trained")
    training_config: Optional[TrainingConfig] = Field(default=None, description="Training configuration used")
    
    model_results: Dict[str, ModelResult] = Field(
        default_factory=dict,
        description="Results for each trained model"
    )
    
    model_scores: Dict[str, float] = Field(
        default_factory=dict,
        description="Simplified model name to score mapping"
    )
    
    training_time_seconds: Optional[float] = Field(default=None, ge=0.0, description="Total training time")
    
    @field_validator('task_type')
    @classmethod
    def validate_task_type(cls, v):
        if v not in ['classification', 'regression']:
            raise ValueError('task_type must be "classification" or "regression"')
        return v
    
    @field_validator('best_score')
    @classmethod
    def validate_best_score(cls, v):
        if v is not None and (v < 0 or v > 1):
            raise ValueError('best_score must be between 0 and 1')
        return v
    
    @property
    def best_model(self) -> Optional[str]:
        """Alias for best_model_name for backward compatibility."""
        return self.best_model_name
    
    @property
    def successful_models(self) -> List[str]:
        """List of models that trained successfully."""
        return [
            name for name, result in self.model_results.items()
            if result.error is None
        ]
    
    @property
    def failed_models(self) -> List[str]:
        """List of models that failed to train."""
        return [
            name for name, result in self.model_results.items()
            if result.error is not None
        ]
    
    @property
    def model_ranking(self) -> List[tuple[str, float]]:
        """Models ranked by CV score (descending)."""
        scores = [
            (name, result.cv_score)
            for name, result in self.model_results.items()
            if result.error is None
        ]
        return sorted(scores, key=lambda x: x[1], reverse=True)
    
    @property
    def score_variance(self) -> float:
        """Variance in model scores (indicates problem difficulty)."""
        scores = [r.cv_score for r in self.model_results.values() if r.error is None]
        if len(scores) < 2:
            return 0.0
        mean = sum(scores) / len(scores)
        return sum((s - mean) ** 2 for s in scores) / len(scores)
    
    model_config = {
        "json_schema_extra": {
            "description": "Training summary schema for model training artifacts",
            "examples": [{
                "schema_version": "1.0.0",
                "created_at": "2026-02-22T10:35:00",
                "task_type": "classification",
                "best_model_name": "xgboost",
                "best_score": 0.92,
                "models_trained": 3,
                "training_config": {
                    "algorithms": ["logistic_regression", "random_forest", "xgboost"],
                    "cv_folds": 5,
                    "scoring_metric": "accuracy",
                    "hyperparameter_tuning": True
                },
                "model_results": {
                    "xgboost": {"cv_score": 0.92, "best_params": {"n_estimators": 100}},
                    "random_forest": {"cv_score": 0.89, "best_params": {"n_estimators": 50}}
                }
            }]
        },
        "extra": "forbid",
    }
