"""Suggest command for ML Assistant CLI.

Provides AI-powered suggestions for improving ML pipelines using the
Meta-ML recommendation engine with fallback to rule-based analysis.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, BarColumn, TextColumn
from rich.table import Table

from mlcli.core.exceptions import DataError
from mlcli.core.suggestion_model.model import MLSuggestionEngine
from mlcli.core.telemetry import TelemetryCollector
from mlcli.meta_ml import SuggestionEngine
from mlcli.utils.logging import get_logger

logger = get_logger(__name__)
console = Console()

app = typer.Typer()


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    data_profile: Optional[Path] = typer.Option(None, "--data-profile", help="Data profile JSON file"),
    evaluation_report: Optional[Path] = typer.Option(None, "--evaluation", help="Evaluation report JSON file"),
    training_summary: Optional[Path] = typer.Option(None, "--training", help="Training summary JSON file"),
    use_ml: bool = typer.Option(True, "--ml/--rules", help="Use ML engine or fallback to rules"),
    top_k: int = typer.Option(5, "--top-k", "-k", help="Number of suggestions to show"),
) -> None:
    """Get AI-powered suggestions for improving your ML pipeline."""
    
    config = ctx.obj["config"]
    project_dir = ctx.obj["project_dir"]
    
    if data_profile is None:
        data_profile = project_dir / "data" / "processed" / "data_profile.json"
    
    if evaluation_report is None:
        evaluation_report = project_dir / "reports" / "evaluation_report.json"
    
    if training_summary is None:
        training_summary = project_dir / "models" / "training_summary.json"
    
    telemetry = TelemetryCollector(project_dir)
    
    console.print("[blue]Analyzing your ML pipeline...[/blue]")
    
    reports = {}
    missing = []
    
    if data_profile.exists():
        with open(data_profile, 'r') as f:
            reports['data_profile'] = json.load(f)
        console.print("[green]OK[/green] Loaded data profile")
    else:
        missing.append(("data_profile.json", "mlcli preprocess"))
    
    if evaluation_report.exists():
        with open(evaluation_report, 'r') as f:
            reports['evaluation'] = json.load(f)
        console.print("[green]OK[/green] Loaded evaluation report")
    else:
        missing.append(("evaluation_report.json", "mlcli evaluate"))
    
    if training_summary.exists():
        with open(training_summary, 'r') as f:
            reports['training'] = json.load(f)
        console.print("[green]OK[/green] Loaded training summary")
    
    if missing:
        console.print("\n[yellow]Missing required artifacts:[/yellow]")
        for filename, command in missing:
            console.print(f"  - {filename} (run: [cyan]{command}[/cyan])")
        console.print("\n[dim]Run the missing commands first to get better suggestions.[/dim]")
    
    if not reports:
        raise typer.Exit(0)
    
    suggestions = _generate_suggestions(reports, config, use_ml, top_k)
    
    _display_suggestions(suggestions)
    
    _save_suggestions(project_dir, suggestions)
    
    if 'data_profile' in reports and 'evaluation' in reports:
        session_id = telemetry.log_suggestions_shown(
            suggestions.get("ml_suggestions", []),
            context={"source": "meta_ml" if use_ml else "rules"}
        )
        _save_session_id(project_dir, session_id)
    
    console.print(f"\n[dim]Suggestions generated by: {suggestions.get('source', 'unknown')}[/dim]")


def _generate_suggestions(
    reports: Dict[str, Any], 
    config: Any,
    use_ml: bool,
    top_k: int
) -> Dict[str, Any]:
    """Generate comprehensive suggestions."""
    
    suggestions = {
        "ml_suggestions": [],
        "data_suggestions": [],
        "model_suggestions": [],
        "performance_suggestions": [],
        "deployment_suggestions": [],
        "priority_actions": [],
        "source": "rules",
    }
    
    if 'data_profile' in reports and 'evaluation' in reports and use_ml:
        try:
            model_path = Path(__file__).parent.parent / "core" / "suggestion_model" / "data" / "suggestion_model_v2.pkl"
            
            if not model_path.exists():
                model_path = Path(__file__).parent.parent / "core" / "suggestion_model" / "data" / "suggestion_model.pkl"
            
            engine = SuggestionEngine(model_path=model_path if model_path.exists() else None)
            
            ml_suggestions = engine.predict(
                data_profile=reports['data_profile'],
                evaluation_report=reports['evaluation'],
                top_k=top_k,
                confidence_threshold=0.25,
            )
            
            suggestions["ml_suggestions"] = ml_suggestions
            suggestions["source"] = "ml" if engine.is_ready() else "rules"
            
            if engine.is_ready():
                console.print("[green]OK[/green] Using Meta-ML engine")
            else:
                console.print("[yellow]![/yellow] Using rule-based engine")
                
        except Exception as e:
            logger.warning(f"ML engine failed: {e}")
            console.print(f"[yellow]![/yellow] ML engine unavailable, using rules")
    
    if 'data_profile' in reports:
        data_suggestions = _analyze_data_quality(reports['data_profile'])
        suggestions["data_suggestions"].extend(data_suggestions)
    
    if 'training' in reports:
        model_suggestions = _analyze_model_performance(reports['training'])
        suggestions["model_suggestions"].extend(model_suggestions)
    
    if 'evaluation' in reports:
        performance_suggestions = _analyze_evaluation_results(reports['evaluation'])
        suggestions["performance_suggestions"].extend(performance_suggestions)
    
    deployment_suggestions = _generate_deployment_suggestions(reports, config)
    suggestions["deployment_suggestions"].extend(deployment_suggestions)
    
    suggestions["priority_actions"] = _determine_priority_actions(suggestions)
    
    return suggestions


def _analyze_data_quality(data_profile: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Analyze data quality and suggest improvements."""
    suggestions = []
    
    original_shape = data_profile.get('original_shape', [0, 0])
    n_samples, n_features = original_shape
    
    if n_samples < 1000:
        suggestions.append({
            "category": "Data Size",
            "priority": "High",
            "issue": f"Small dataset ({n_samples} samples)",
            "suggestion": "Collect more data or use data augmentation",
            "impact": "More data typically leads to better model performance",
            "action": "Add more samples to data/raw/",
        })
    
    if n_features > n_samples:
        suggestions.append({
            "category": "Dimensionality",
            "priority": "High",
            "issue": f"More features ({n_features}) than samples ({n_samples})",
            "suggestion": "Apply feature selection or dimensionality reduction",
            "impact": "Reduces overfitting and improves generalization",
            "action": "Use PCA or SelectKBest to reduce dimensions",
        })
    
    missing_pct = data_profile.get('missing_percentage', {})
    if missing_pct:
        max_missing = max(missing_pct.values())
        if max_missing > 30:
            high_missing_cols = [k for k, v in missing_pct.items() if v > 30]
            suggestions.append({
                "category": "Missing Values",
                "priority": "High",
                "issue": f"High missing values in {len(high_missing_cols)} columns",
                "suggestion": "Improve imputation or remove columns with >50% missing",
                "impact": "More reliable training data",
                "action": "Review imputation strategy in mlcli.yaml",
            })
    
    return suggestions


def _analyze_model_performance(training_summary: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Analyze model training results."""
    suggestions = []
    
    model_scores = training_summary.get('model_scores', {})
    best_score = training_summary.get('best_score', 0)
    task_type = training_summary.get('task_type', 'classification')
    
    threshold = 0.7 if task_type == 'classification' else 0.5
    if best_score < threshold:
        suggestions.append({
            "category": "Model Performance",
            "priority": "High",
            "issue": f"Low {task_type} performance ({best_score:.3f})",
            "suggestion": "Try advanced algorithms or ensemble methods",
            "impact": "Significant improvement in accuracy",
            "action": "Add 'xgboost' to model.algorithms in mlcli.yaml",
        })
    
    if len(model_scores) < 3:
        suggestions.append({
            "category": "Model Selection",
            "priority": "Medium",
            "issue": "Limited model algorithms tested",
            "suggestion": "Try more diverse algorithms",
            "impact": "Find the best algorithm for your problem",
            "action": "Enable hyperparameter_tuning in mlcli.yaml",
        })
    
    return suggestions


def _analyze_evaluation_results(evaluation_report: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Analyze evaluation results."""
    suggestions = []
    
    metrics = evaluation_report.get('metrics', {})
    task_type = evaluation_report.get('task_type', 'classification')
    
    if task_type == 'classification':
        precision = metrics.get('precision', 0)
        recall = metrics.get('recall', 0)
        
        if abs(precision - recall) > 0.2:
            suggestions.append({
                "category": "Class Imbalance",
                "priority": "High",
                "issue": f"Precision ({precision:.3f}) vs Recall ({recall:.3f}) gap",
                "suggestion": "Address class imbalance with SMOTE or class weights",
                "impact": "Better balanced performance",
                "action": "Set imbalance_strategy: smote in mlcli.yaml",
            })
        
        accuracy = metrics.get('accuracy', 0)
        if accuracy < 0.8:
            suggestions.append({
                "category": "Performance",
                "priority": "High",
                "issue": f"Low accuracy ({accuracy:.3f})",
                "suggestion": "Try feature engineering or hyperparameter tuning",
                "impact": "Improved prediction accuracy",
                "action": "Enable hyperparameter_tuning: true",
            })
    
    return suggestions


def _generate_deployment_suggestions(reports: Dict[str, Any], config: Any) -> List[Dict[str, Any]]:
    """Generate deployment suggestions."""
    suggestions = []
    
    suggestions.append({
        "category": "Deployment",
        "priority": "Medium",
        "issue": "Model ready for deployment",
        "suggestion": "Package with BentoML for cloud deployment",
        "impact": "Easy deployment to cloud platforms",
        "action": "Run: mlcli package",
    })
    
    return suggestions


def _determine_priority_actions(suggestions: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Determine top priority actions."""
    
    all_suggestions = []
    for category, suggestion_list in suggestions.items():
        if category not in ("priority_actions", "source", "ml_suggestions"):
            all_suggestions.extend(suggestion_list)
    
    priority_order = {"High": 3, "Medium": 2, "Low": 1}
    all_suggestions.sort(
        key=lambda x: (priority_order.get(x.get("priority", "Low"), 1), x.get("confidence", 0)), 
        reverse=True
    )
    
    return all_suggestions[:5]


def _display_suggestions(suggestions: Dict[str, Any]) -> None:
    """Display suggestions with confidence visualization."""
    
    console.print("\n" + "=" * 60)
    console.print("[bold]AI-Powered Improvement Suggestions[/bold]")
    console.print("=" * 60)
    
    ml_suggestions = suggestions.get("ml_suggestions", [])
    
    if ml_suggestions:
        console.print("\n[bold cyan]ML-Powered Recommendations[/bold cyan]")
        
        for i, suggestion in enumerate(ml_suggestions, 1):
            confidence = suggestion.get("confidence", 0.5)
            
            console.print(f"\n[bold]{i}. {suggestion.get('suggestion', 'Unknown').replace('_', ' ').title()}[/bold]")
            
            with Progress(
                TextColumn("[progress.description]{task.description}"),
                BarColumn(complete_style="green", finished_style="green"),
                TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
                console=console,
                transient=False
            ) as progress:
                progress.add_task("Confidence: ", total=100, completed=confidence * 100)
            
            if confidence >= 0.8:
                level = "[green]High confidence[/green]"
            elif confidence >= 0.5:
                level = "[yellow]Medium confidence[/yellow]"
            else:
                level = "[dim]Low confidence[/dim]"
            
            console.print(f"  {level}")
            console.print(f"  [bold]Issue:[/bold] {suggestion.get('issue', 'N/A')}")
            console.print(f"  [bold]Impact:[/bold] {suggestion.get('impact', 'N/A')}")
            console.print(f"  [bold]Action:[/bold] [dim]{suggestion.get('action', 'N/A')}[/dim]")
    
    priority_actions = suggestions.get("priority_actions", [])
    if priority_actions:
        console.print("\n[bold red]Top Priority Actions[/bold red]")
        
        for i, action in enumerate(priority_actions[:3], 1):
            priority = action.get("priority", "Low")
            priority_color = {"High": "red", "Medium": "yellow", "Low": "blue"}.get(priority, "white")
            
            console.print(f"\n{i}. [{priority_color}]{priority}[/{priority_color}] - {action.get('category', 'General')}")
            console.print(f"   [bold]Issue:[/bold] {action.get('issue', 'N/A')}")
            console.print(f"   [bold]Action:[/bold] {action.get('action', action.get('suggestion', 'N/A'))}")
    
    console.print("\n" + "=" * 60)


def _save_suggestions(project_dir: Path, suggestions: Dict[str, Any]) -> None:
    """Save suggestions to file."""
    suggestions_path = project_dir / "reports" / "suggestions.json"
    suggestions_path.parent.mkdir(parents=True, exist_ok=True)
    
    save_data = {k: v for k, v in suggestions.items() if k != "source"}
    
    with open(suggestions_path, 'w') as f:
        json.dump(save_data, f, indent=2, default=str)
    
    console.print(f"\n[green]OK[/green] Suggestions saved to: {suggestions_path}")


def _save_session_id(project_dir: Path, session_id: str) -> None:
    """Save session ID for telemetry tracking."""
    session_file = project_dir / ".mlcli" / "last_suggestion_session"
    session_file.parent.mkdir(parents=True, exist_ok=True)
    session_file.write_text(session_id)
